name: base
description: "Base Flutter Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.1
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_remote_config: ^6.1.4
  
  # State Management
  flutter_riverpod: ^3.2.0
  
  # Utils
  http: ^1.6.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4
  purchases_flutter: ^9.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true